### ISSUE TITLE
Project name - assembly name mismatch

### ISSUE THREAD

**Issue by kotwin** [drOpen/DrCommon#2]
DrDataSx: project is named with Sx at the end, but assembly and default name space are with Se:

Master branch:
https://github.com/drOpen/DrCommon/blob/da3f0c3cf58db48faa753a7b6ab89ec8c1346ee2/DrData/DrDataSx/DrDataSx.csproj#L10-L11
Integration branch:
https://github.com/drOpen/DrCommon/blob/1a8b210949906967e56e93048c383adcc7adfd33/DrData/DrDataSx/DrDataSx.csproj#L10-L11
Com branch:
https://github.com/drOpen/DrCommon/blob/68aba480444987456be7584b8161a03eb72fa1e3/DrData/DrDataSx/DrDataSx.csproj#L10-L11

**Comment by drOpen** [comment]
fixed in the 27afcea907c0b847c3e070053ba1ff33f2833e41
